
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DIVIDE = 43;
  public static final int BOOLEAN_LITERAL_FALSE = 55;
  public static final int STRING_LITERAL = 59;
  public static final int POWER = 45;
  public static final int POOL = 24;
  public static final int CONCATENATE = 53;
  public static final int QUESTIONMARK = 39;
  public static final int INTEGER = 2;
  public static final int LPAREN = 28;
  public static final int LESS = 49;
  public static final int MINUS = 41;
  public static final int BOOLEAN_LITERAL_TRUE = 54;
  public static final int CHARACTER = 3;
  public static final int RPAREN = 29;
  public static final int OROR = 51;
  public static final int IMPLICATION = 62;
  public static final int CHARACTER_LITERAL = 61;
  public static final int NOT = 52;
  public static final int RANGLEBRACKT = 38;
  public static final int SEMICOLON = 34;
  public static final int RATIONAL = 4;
  public static final int IN = 22;
  public static final int COMMA = 35;
  public static final int ANDAND = 50;
  public static final int PLUS = 40;
  public static final int TYPEDEF = 11;
  public static final int LOOP = 23;
  public static final int LESSEQ = 48;
  public static final int ASSIGN = 44;
  public static final int MAIN = 26;
  public static final int IF = 15;
  public static final int DOT = 37;
  public static final int EOF = 0;
  public static final int BOOLEAN = 6;
  public static final int RETURN = 19;
  public static final int DICTIONARY = 9;
  public static final int error = 1;
  public static final int EQEQ = 46;
  public static final int NULL = 14;
  public static final int BREAK = 25;
  public static final int RATIONAL_LITERAL = 58;
  public static final int TOP = 7;
  public static final int LBRACK = 32;
  public static final int TIMES = 42;
  public static final int COLON = 36;
  public static final int ENDIF = 16;
  public static final int LBRACE = 30;
  public static final int ELSE = 17;
  public static final int READ = 20;
  public static final int RBRACK = 33;
  public static final int FLOAT = 5;
  public static final int THEN = 18;
  public static final int RBRACE = 31;
  public static final int FUNCTIONDEF = 12;
  public static final int STRING = 8;
  public static final int ALIAS = 13;
  public static final int SEQUENCE = 10;
  public static final int FLOAT_LITERAL = 57;
  public static final int PRINT = 21;
  public static final int LENGTH = 27;
  public static final int NOTEQ = 47;
  public static final int IDENTIFIER = 60;
  public static final int INTEGER_LITERAL = 56;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "INTEGER",
  "CHARACTER",
  "RATIONAL",
  "FLOAT",
  "BOOLEAN",
  "TOP",
  "STRING",
  "DICTIONARY",
  "SEQUENCE",
  "TYPEDEF",
  "FUNCTIONDEF",
  "ALIAS",
  "NULL",
  "IF",
  "ENDIF",
  "ELSE",
  "THEN",
  "RETURN",
  "READ",
  "PRINT",
  "IN",
  "LOOP",
  "POOL",
  "BREAK",
  "MAIN",
  "LENGTH",
  "LPAREN",
  "RPAREN",
  "LBRACE",
  "RBRACE",
  "LBRACK",
  "RBRACK",
  "SEMICOLON",
  "COMMA",
  "COLON",
  "DOT",
  "RANGLEBRACKT",
  "QUESTIONMARK",
  "PLUS",
  "MINUS",
  "TIMES",
  "DIVIDE",
  "ASSIGN",
  "POWER",
  "EQEQ",
  "NOTEQ",
  "LESSEQ",
  "LESS",
  "ANDAND",
  "OROR",
  "NOT",
  "CONCATENATE",
  "BOOLEAN_LITERAL_TRUE",
  "BOOLEAN_LITERAL_FALSE",
  "INTEGER_LITERAL",
  "FLOAT_LITERAL",
  "RATIONAL_LITERAL",
  "STRING_LITERAL",
  "IDENTIFIER",
  "CHARACTER_LITERAL",
  "IMPLICATION"
  };
}

